Comunidad/proyecto/actividades/urls.py
from django.urls import path
from . import views

app_name = "actividades"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('actividad/', views.actividads, name="activi"),
    path('actas_agregar/', views.agregar_acta, name="actas"),
    path('listar_nuevos/', views.list_actas, name="list_act"),
    path('deletema/<str:acta_id>/', views.eliminar_actas, name='eliminar_acta'),
    path('updatema/<int:acta_id>/', views.actualizar_acta, name='acta_actuali'),





# ---------------------ACTIVIDADES EDUCATIVAS-------------------
    path('agregar_actividad/', views.agregar_actividad, name="agregar_act"),
    path('listarm/', views.listar_miem, name="lista"),
    path('listarn/', views.get_tiempo_data, name="datatime"),
    path('lista_edu/', views.lista_educa, name="lista_educativa"),
    path('deleteact/<str:actividad_id>/', views.eliminar_actividades, name='eliminar_actividad'),
    path('updateact/<int:actividad_id>/', views.actualizar_actividad, name='actividad_actuali'),    
    # ---------------------NO ACTIVIDADES -------------------
    path('agregar_noactividad/', views.agregar_noactividad, name="agregar_noact"),
    path('lista_noedu/', views.lista_noeduca, name="lista_noeducativa"),
    path('deletenoact/<str:noactividad_id>/', views.eliminar_noactividades, name='eliminar_noactividad'),
    path('updatenoact/<int:noactividad_id>/', views.actualizar_noactividad, name='noactividad_actuali'), 

    


]

Comunidad/proyecto/eventos/urls.py
from django.urls import path
from . import views

app_name = "eventos"
urlpatterns = [

#---------------------EVENTOS------------------------    
    path('eventos_agregar/', views.agregar_evento, name="eventos"),
    path('listar_eventos/', views.list_eventos, name="list_evento"),
    path('deleteeve/<str:evento_id>/', views.eliminar_eventos, name='eliminar_evento'),
    path('updateeve/<int:evento_id>/', views.actualizar_evento, name='evento_actuali'),




    


]

Comunidad/proyecto/gastos/urls.py
from django.urls import path
from . import views

app_name = "gastos"
urlpatterns = [

#---------------------EVENTOS------------------------    
    path('gastos_agregar/', views.agregar_gasto, name="gastos"),
    path('listar_gastos/', views.list_gastos, name="list_gasto"),
    path('deletegas/<str:gasto_id>/', views.eliminar_gastos, name='eliminar_gasto'),
    path('updategas/<int:gasto_id>/', views.actualizar_gasto, name='gastos_actuali'),






    


]

Comunidad/proyecto/inicio/urls.py
from django.urls import path
from . import views

app_name = "inicio"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('sssss', views.home, name="activi"),


    

]

Comunidad/proyecto/miembros/urls.py
from django.urls import path
from . import views


app_name = "miembros"
urlpatterns = [
    path('miembros/', views.agregar_miembros, name="agregar_miembro"),
    path('listar_miembros/', views.listar_m, name="lista_miembro"),
    path('delete/<str:miembro_id>/', views.eliminar_miembros, name='eliminar_miembro'),
    path('update/<int:miembro_id>/', views.actualizar_miembro, name='miembros_actuali'),





]

Comunidad/proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m




urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('autenticaci', include('auntenticacion.urls')),
    path('miembros/', include('miembros.urls')),
    path('actividades/', include('actividades.urls')),
    path('eventos/', include('eventos.urls')),
    path('gastos/', include('gastos.urls')),
    path('inicios/', include('inicio.urls')),

    path('',view_m.home, name="home"),


# ---------------------ACTIVIDADES EVENTOS-------------------

    

# ---------------------ACTIVIDADES EDUCATIVAS-------------------

    
    # ---------------------NO ACTIVIDADES -------------------

    
 



     
    
  
]

Comunidad/proyecto/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title> {% block title %}{% endblock %} |Comunidad Islámica Aldaawa</title>

    <!-- Estilos y fuentes del template  -->
  

    <link href="{% static 'bas/css/clean-blog.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'bas/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'bas/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    {% block stylesheets %}{% endblock stylesheets %}
  </head>

  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">      
        <a class="navbar-brand" href="{% url 'inicio:activi' %}">Comunidad Islámica Aldaawa</a>        
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menú
          <i class="fa fa-bars"></i>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'inicio:activi' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'miembros:lista_miembro' %}">Miembros</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'actividades:activi' %}">Actividades</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'eventos:list_evento' %}">Eventos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gastos:list_gasto' %}">Gastos</a>
            </li>           
          </ul>                      
        </div>       
      </div>
              <div>
                <ul class="navbar-nav ml-auto">
                  <div class="topbar-divider d-none d-sm-block"></div>
                  <li class="nav-item dropdown no-arrow">
                      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.username}}</span>
                          <img class="img-profile rounded-circle"
                              src="{% static 'inicio/img/Customer.png' %}">
                      </a>
                      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                          aria-labelledby="userDropdown">
                          {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
                          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                              <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                              Cerrar Sesión
                          </a>
                      </div>
                  </li>
                </ul>
              <div>            
    </nav>
     


    <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %} {% endblock %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              {% block headers %} {% endblock %}                
            </div>
          </div>
        </div>
      </div>
     </header>
    {% include 'base/messages.html' with messages=messages%}
    
    <!-- Contenido -->
     <div class="container" style ="width: 100%;">  
        {% block content %}{% endblock %}
    </div>
   
    {% if request.path != "/" %} <hr> {% endif %}


    <!-- Pié de página -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
               <p>"El camino hacia la humildad es la humillación"</p>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; 2023 · Comunidad Islámica Aldaawa </p>
          </div>
        </div>
      </div>
    </footer>

    {% include 'auth/logout_modal.html' %}
    <script src="{% static 'bas/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bas/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'bas/js/clean-blog.min.js' %}"></script>
    {% block javascripts %}{% endblock javascripts %}


  </body>

</html>

Comunidad/proyecto/templates/base/messages.html
{% load static %}
{% if messages %}
<div class="form-group">
    {% for message in messages %}
    <div id="message_js" class="alert alert-{{message.extra_tags}} alert-dissmissible fade-show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endfor %}
</div>     
{% endif %}