Comunidad/proyecto/gastos/urls.py
from django.urls import path
from . import views

app_name = "gastos"
urlpatterns = [

#---------------------EVENTOS------------------------    
    path('gastos_agregar/', views.agregar_gasto, name="gastos"),
    path('listar_gastos/', views.list_gastos, name="list_gasto"),
    path('deletegas/<str:gasto_id>/', views.eliminar_gastos, name='eliminar_gasto'),
    path('updategas/<int:gasto_id>/', views.actualizar_gasto, name='gastos_actuali'),






    


]

Comunidad/proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m




urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('autenticaci', include('auntenticacion.urls')),
    path('miembros/', include('miembros.urls')),
    path('actividades/', include('actividades.urls')),
    path('eventos/', include('eventos.urls')),
    path('gastos/', include('gastos.urls')),
    path('inicios/', include('inicio.urls')),

    path('',view_m.home, name="home"),


# ---------------------ACTIVIDADES EVENTOS-------------------

    

# ---------------------ACTIVIDADES EDUCATIVAS-------------------

    
    # ---------------------NO ACTIVIDADES -------------------

    
 



     
    
  
]

Comunidad/proyecto/gastos/models.py
from django.db import models
from eventos.models import evento

class gasto(models.Model):
     presupuesto = models.TextField( null=False, verbose_name="Presupuesto")
     transporte = models.TextField( null=False, verbose_name="Trasporte")
     personal = models.TextField( null=False,  verbose_name="Personal")
     combustible = models.TextField( null=False,  verbose_name="Combustible")
     alquiler = models.TextField( null=False,  verbose_name="Alquiler")
     viaticos = models.TextField( null=False,  verbose_name="Viaticos")
     donaciones = models.TextField( null=False,  verbose_name="Donaciones")
     otros = models.TextField(null=False,  verbose_name="Otros")
     totalgastado=models.TextField( null=False, verbose_name="Totalgastado")
     residuo = models.TextField( null=False, verbose_name="Residuo")
     eventoa = models.ForeignKey(evento, on_delete=models.CASCADE)

     def __str__(self):
        return self.nombre
    
     class Meta:
       db_table ='gasto'
       verbose_name= 'gasto'
       verbose_name_plural= 'gastos'
       ordering = ['-id']                 

Comunidad/proyecto/gastos/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from eventos.models import evento
from gastos.models import gasto
from django.contrib.auth.decorators import login_required
from decimal import Decimal  
import re






#-----------------------------APARTADO DE MODULO DE EVENTOS---------------------------------------------
#----------------------------------------------------------------------------------------------------------------------




#Lista los Eventos ya creados en la base de datos
@login_required(login_url="auth/login/")
def list_gastos(request):
    query = request.GET.get('q', '')
    gastos = gasto.objects.filter(  
        Q(eventoa__titulo__icontains=query)        
    )
    context = {
        "active_icon": "gastos",
        "gastos":gastos,
        "query": query,
    }
    return render(request, "gasto/gastos.html", context)






@login_required(login_url="auth/login/")
def eliminar_gastos(request, gasto_id):
    try:
        Gasto = gasto.objects.get(pk=gasto_id)
        Gasto.delete()
        messages.success(request, '¡Gasto eliminado!', extra_tags="success")
        return redirect('gastos:list_gasto')  
    except Exception as e:
        messages.error(request, '¡Hubo un error durante la eliminación!' + str(e), extra_tags="danger")
        return redirect('gastos:list_gasto')
    





#Agrega a la base de datos los Eventos, funcion para insertar 
@login_required(login_url="auth/login/")
def agregar_gasto(request):
    eventos = evento.objects.all()

    if request.method == 'POST':
        data = request.POST

        evento_id = data.get('evento')

        # Verificar si ya existe un gasto asociado al evento
        if gasto.objects.filter(eventoa__id=evento_id).exists():
            messages.error(request, 'Ya existe un gasto registrado para este evento.', extra_tags="danger")
            return redirect('gastos:list_gasto')

        # Elimina "Q." de los valores ingresados
        presupuesto = re.sub(r'[^\d.]', '', data.get('presupuesto'))
        transporte = re.sub(r'[^\d.]', '', data.get('transporte'))
        personal = re.sub(r'[^\d.]', '', data.get('personal'))
        combustible = re.sub(r'[^\d.]', '', data.get('combustible'))
        alquiler = re.sub(r'[^\d.]', '', data.get('alquiler'))
        viaticos = re.sub(r'[^\d.]', '', data.get('viaticos'))
        donaciones = re.sub(r'[^\d.]', '', data.get('donaciones'))
        otros = re.sub(r'[^\d.]', '', data.get('otros'))

        # Validación de los valores ingresados
        if not presupuesto or \
           not transporte or \
           not personal or \
           not combustible or \
           not alquiler or \
           not viaticos or \
           not donaciones or \
           not otros:
            messages.error(request, 'Los valores ingresados deben ser numéricos.', extra_tags="danger")
            return redirect('gastos:gastos')

        # Convertir los valores a números de punto flotante
        presupuesto = float(presupuesto)
        transporte = float(transporte)
        personal = float(personal)
        combustible = float(combustible)
        alquiler = float(alquiler)
        viaticos = float(viaticos)
        donaciones = float(donaciones)
        otros = float(otros)

        evento_obj = evento.objects.get(pk=evento_id)

        # Calcula el totalgastado y residuo
        totalgastado = presupuesto - (transporte + personal + combustible + alquiler + viaticos + donaciones + otros)
        residuo = presupuesto - totalgastado

        nuevo_evento = gasto(
            eventoa=evento_obj,
            presupuesto=presupuesto,
            transporte=transporte,
            personal=personal,
            combustible=combustible,
            alquiler=alquiler,
            viaticos=viaticos,
            donaciones=donaciones,
            otros=otros,
            totalgastado=totalgastado,
            residuo=residuo
        )
        nuevo_evento.save()

        messages.success(request, 'Gasto creado con éxito!', extra_tags="success")
        return redirect('gastos:gastos')

    return render(request, "gasto/agregar_gasto.html", {
        'eventos': eventos,
    })











#Actualiza un gasto de un evento realizado en la mezquita aldaawa
@login_required(login_url="auth/login/")
def actualizar_gasto(request, gasto_id):
    eventos = evento.objects.all()

    try:
        gasto_obj = gasto.objects.get(pk=gasto_id)

        if request.method == 'POST':
            data = request.POST.copy()  # Crea una copia mutable de request.POST

            evento_id = data.get('evento')

            if gasto_obj.eventoa.id != int(evento_id):
                # Verifica si ya existe un gasto asociado al nuevo evento
                if gasto.objects.filter(eventoa__id=evento_id).exclude(id=gasto_obj.id).exists():
                    messages.error(request, 'Ya existe un gasto registrado para este evento.', extra_tags="danger")
                    return redirect('gastos:list_gasto')

                evento_obj = evento.objects.get(pk=evento_id)
                gasto_obj.eventoa = evento_obj

            # Reemplaza comas con puntos en los valores
            for key in ['presupuesto', 'transporte', 'personal', 'combustible', 'alquiler', 'viaticos', 'donaciones', 'otros']:
                data[key] = data[key].replace(',', '.')

            # Validación y conversión de valores a Decimal
            try:
                presupuesto = Decimal(data.get('presupuesto'))
                transporte = Decimal(data.get('transporte'))
                personal = Decimal(data.get('personal'))
                combustible = Decimal(data.get('combustible'))
                alquiler = Decimal(data.get('alquiler'))
                viaticos = Decimal(data.get('viaticos'))
                donaciones = Decimal(data.get('donaciones'))
                otros = Decimal(data.get('otros'))

                # Calcula el totalgastado y residuo
                totalgastado = presupuesto - (transporte + personal + combustible + alquiler + viaticos + donaciones + otros)
                residuo = presupuesto - totalgastado

                # Asigna los valores calculados
                gasto_obj.presupuesto = presupuesto
                gasto_obj.transporte = transporte
                gasto_obj.personal = personal
                gasto_obj.combustible = combustible
                gasto_obj.alquiler = alquiler
                gasto_obj.viaticos = viaticos
                gasto_obj.donaciones = donaciones
                gasto_obj.otros = otros
                gasto_obj.totalgastado = totalgastado
                gasto_obj.residuo = residuo
            except Exception as e:
                messages.error(request, 'Los valores ingresados deben ser numéricos.', extra_tags="danger")
                return redirect('gastos:list_gasto')

            gasto_obj.save()

            messages.success(request, 'Gasto actualizado con éxito!', extra_tags="success")
            return redirect('gastos:list_gasto')

        return render(request, "gasto/actualizar_gasto.html", {
            'gasto': gasto_obj,
            'eventos': eventos,
        })

    except gasto.DoesNotExist:
        messages.error(request, 'El gasto que intentas actualizar no existe.', extra_tags="danger")
        return redirect('gastos:list_gasto')
    except evento.DoesNotExist:
        messages.error(request, 'El evento asociado no existe.', extra_tags="danger")
        return redirect('gastos:list_gasto')
    except Exception as e:
        messages.error(request, 'Error al actualizar el gasto: ' + str(e), extra_tags="danger")
        return redirect('gastos:list_gasto')

Comunidad/proyecto/templates/gasto/actualizar_gasto.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'mie/css/miembros.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'act/css/lista_act.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %} Gastos {% endblock %}

{% block background %}{% static 'gas/img/gasto.jpg' %}{% endblock %}

{% block headers %}<h1>Actualizar Gasto</h1>{% endblock %}

{% block content %}
<div class="member-section">
    <div id="alert-message" style="display: none;"></div>

    <form method="post" id="gasto-form">
        {% csrf_token %}
        <div class="form-group-container">
            <div class="form-group">
                <label for="evento">Evento:</label>
                <select id="evento" name="evento" class="form-control" required readonly>
                    {% for e in eventos %}
                        <option value="{{ e.id }}" {% if e.id == gasto.eventoa.id %}selected{% endif %}>{{ e.titulo }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="presupuesto">PRESUPUESTO:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="presupuesto" name="presupuesto" class="form-control" value="{{ gasto.presupuesto }}" required>
                </div>
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="transporte">Trasnporte:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="transporte" name="transporte" class="form-control" value="{{ gasto.transporte }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="personal">Personal:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="personal" name= "personal" class="form-control" value="{{ gasto.personal }}" required>
                </div>
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="combustible">Combustible:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="combustible" name="combustible" class="form-control" value="{{ gasto.combustible }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="alquiler">Alquiler:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="alquiler" name="alquiler" class="form-control" value="{{ gasto.alquiler }}" required>
                </div>
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="viaticos">Viaticos:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="viaticos" name="viaticos" class="form-control" value="{{ gasto.viaticos }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="donaciones">Donaciones:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="donaciones" name="donaciones" class="form-control" value="{{ gasto.donaciones }}" required>
                </div>
            </div>
        </div>

        <div class="form-group-container">
            <div class="form-group">
                <label for="otros">Otros:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="otros" name="otros" class="form-control" value="{{ gasto.otros }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="totalgastado">TOTAL GASTADO:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="totalgastado" name="totalgastado" class="form-control" value="{{ gasto.totalgastado }}" required readonly>
                </div>
            </div>
            <div class="form-group">
                <label for="residuo">SOBRANTE:</label>
                <div class="input-with-prefix">
                    <span class="currency-symbol">Q.</span>
                    <input type="text" id="residuo" name="residuo" class="form-control" value="{{ gasto.residuo }}" required readonly>
                </div>
            </div>
        </div>

        <div class="button-group">
             <button style= "cursor: pointer;" type="submit" class="btn btn-primary agregar-button">Actualizar Gasto</button>
            <a href="{% url 'gastos:list_gasto' %}" class="btn btn-primary listar-button">Listar</a>
        </div>
    </form>
</div>
{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    // Obtén referencias a los campos de entrada necesarios
    const presupuestoInput = document.getElementById('presupuesto');
    const gastoInputs = [
        document.getElementById('transporte'),
        document.getElementById('personal'),
        document.getElementById('combustible'),
        document.getElementById('alquiler'),
        document.getElementById('viaticos'),
        document.getElementById('donaciones'),
        document.getElementById('otros')
    ];
    const totalGastadoInput = document.getElementById('totalgastado');
    const residuoInput = document.getElementById('residuo');

    // Agrega un evento de escucha a cada campo de entrada de gasto para actualizar el total
    gastoInputs.forEach(function (input) {
        input.addEventListener('input', calcularTotalYSobrante);
    });

    // Agrega un evento de escucha al campo de presupuesto para calcular el total y el sobrante
    presupuestoInput.addEventListener('input', calcularTotalYSobrante);

    function calcularTotalYSobrante() {
        // Parsea el presupuesto y los gastos a números
        const presupuesto = parseFloat(presupuestoInput.value) || 0;
        const gastos = gastoInputs.reduce(function (total, input) {
            const valor = parseFloat(input.value) || 0;
            return total + valor;
        }, 0);

        // Calcula el total y el sobrante
         // Calcula el total y el sobrante
            const total = gastos.toFixed(2); // Redondea el total a 2 decimales
            const residuo = (presupuesto - gastos).toFixed(2); 
        // Actualiza los campos de salida con los resultados
             totalGastadoInput.value = total;
             residuoInput.value = residuo;

        // Cambia el color del sobrante si el presupuesto se ha sobrepasado
        if (residuo < 0) {
            residuoInput.style.color = 'red';
        } else {
            residuoInput.style.color = 'black';
        }
    }

    // Llama a la función de cálculo al cargar la página
    calcularTotalYSobrante();
});
</script>
{% endblock javascripts %}

Comunidad/proyecto/templates/gasto/gastos.html
{% extends 'base/base.html'%}
{% load static %}
{% block stylesheets %}
<link href="{% static 'act/css/lista_act.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title%} Gastos {% endblock%}   

{% block background %}{% static 'gas/img/gasto.jpg' %}{% endblock %}

{% block headers %}<h1>Lista De Gastos</h1>{% endblock %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'gastos:gastos' %}">
        <button type="button" class="btn btn-info font-weight-bold" style= "cursor: pointer;">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR GASTO
        </button>
    </a>
</div>


<div class="content-container">
    <form method="get" action="{% url 'gastos:list_gasto' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>

    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
            <thead>
                <tr>
                    <th>Evento</th>
                    <th>Presupuesto</th>
                    <th>Trasporte</th>
                    <th>Personal</th>
                    <th>Combustible</th>
                    <th>Alquiler</th>                    
                    <th>Viáticos</th>
                    <th>Donaciones</th>					
                    <th>Otros</th>
                    <th>TOTAL</th> 
                    <th>Sobrante</th>                                                      
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for eve in gastos %}
                    <tr>
                        <td>{{ eve.eventoa.titulo }}</td>  
                        <td style="background-color: #a9eeffb2;">{{ eve.presupuesto }}</td>  
                        <td>{{ eve.transporte }}</td>  
                        <td>{{ eve.personal }}</td> 
                        <td>{{ eve.combustible }}</td> 
                        <td>{{ eve.alquiler }}</td>  
						<td>{{ eve.viaticos }}</td>                           
						<td>{{ eve.donaciones }}</td>  
                        <td>{{ eve.otros }}</td>  
                        <td style="background-color: #9df79d;">{{ eve.residuo }}</td>
                        <td style="background-color: #fcfc9c">{{ eve.totalgastado }}</td> 				                                                    
                        <td class="acciones">
                            <div>
                                <a href="{% url 'gastos:gastos_actuali' eve.id %}" class="btn btn-success" title="Actualizar gasto">
                                    <i class="fas fa-pen"></i> ACTUALIZAR
                                </a>
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarGasto{{ eve.id }}">
                                   ELIMINAR
                                </a>
                            </div>

                            <div class="modal fade" id="eliminarGasto{{  eve.id  }}" tabindex="-1" aria-labelledby="exampleModalLabel{{  eve.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">  
                                            <h5 class="modal-title" id="exampleModalLabel{{  eve.id }}">Eliminar Gasto</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Está seguro de que desea eliminar el gasto a: {{eve.eventoa.titulo}}?
                                        </div>
                                        <div class="modal-footer">
                                            <button style= "cursor: pointer;" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <a id="updateThisURL" rel="delete" href="{% url 'gastos:eliminar_gasto' eve.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}