Comunidad/proyecto/actividades/urls.py
from django.urls import path
from . import views

app_name = "actividades"
urlpatterns = [

#---------------------ACTAS MATRIMONIALES------------------------    
    path('actividad/', views.actividads, name="activi"),
    path('actas_agregar/', views.agregar_acta, name="actas"),
    path('listar_nuevos/', views.list_actas, name="list_act"),
    path('deletema/<str:acta_id>/', views.eliminar_actas, name='eliminar_acta'),
    path('updatema/<int:acta_id>/', views.actualizar_acta, name='acta_actuali'),





# ---------------------ACTIVIDADES EDUCATIVAS-------------------
    path('agregar_actividad/', views.agregar_actividad, name="agregar_act"),
    path('listarm/', views.listar_miem, name="lista"),
    path('listarn/', views.get_tiempo_data, name="datatime"),
    path('lista_edu/', views.lista_educa, name="lista_educativa"),
    path('deleteact/<str:actividad_id>/', views.eliminar_actividades, name='eliminar_actividad'),
    path('updateact/<int:actividad_id>/', views.actualizar_actividad, name='actividad_actuali'),    
    # ---------------------NO ACTIVIDADES -------------------
    path('agregar_noactividad/', views.agregar_noactividad, name="agregar_noact"),
    path('lista_noedu/', views.lista_noeduca, name="lista_noeducativa"),
    path('deletenoact/<str:noactividad_id>/', views.eliminar_noactividades, name='eliminar_noactividad'),
    path('updatenoact/<int:noactividad_id>/', views.actualizar_noactividad, name='noactividad_actuali'), 

    


]

Comunidad/proyecto/gastos/urls.py
from django.urls import path
from . import views

app_name = "gastos"
urlpatterns = [

#---------------------EVENTOS------------------------    
    path('gastos_agregar/', views.agregar_gasto, name="gastos"),
    path('listar_gastos/', views.list_gastos, name="list_gasto"),
    path('deletegas/<str:gasto_id>/', views.eliminar_gastos, name='eliminar_gasto'),
    path('updategas/<int:gasto_id>/', views.actualizar_gasto, name='gastos_actuali'),






    


]

Comunidad/proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio import views as view_m




urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('autenticaci', include('auntenticacion.urls')),
    path('miembros/', include('miembros.urls')),
    path('actividades/', include('actividades.urls')),
    path('eventos/', include('eventos.urls')),
    path('gastos/', include('gastos.urls')),
    path('inicios/', include('inicio.urls')),

    path('',view_m.home, name="home"),


# ---------------------ACTIVIDADES EVENTOS-------------------

    

# ---------------------ACTIVIDADES EDUCATIVAS-------------------

    
    # ---------------------NO ACTIVIDADES -------------------

    
 



     
    
  
]

Comunidad/proyecto/actividades/forms.py
from django import forms
from .models import status , categoria, duracion, curso, clase, tiempo


class statusForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre del status",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = status
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(status, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Estado_actividad"




class tiempoForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre del status",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = tiempo
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(tiempo, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Tiempo_actividad"       





class categoriaForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre de la Categoria",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = categoria
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(categoria, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Categoría_Actividad"




class duracionForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre de la duracion",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = duracion
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(duracion, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Duración_Actividad"        


class cursoForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre del curso",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = curso
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(curso, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Curso_Actividad"   



class claseForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Nombre de la clase",
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = clase
        fields = ['nombre']

    def __init__(self, *args, **kwargs):
        super(clase, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = "Clase_Actividad"                

Comunidad/proyecto/actividades/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Q
from .models import actividad, categoria, curso, clase,status, miembro, maestro, tiempo, nacionalidad
from actividades.models import acta, noactividad
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse





#-----------------------------APARTADO DE MODULO DE ACTIVIDADES EDUCATIVAS---------------------------------------------
#----------------------------------------------------------------------------------------------------------------------




#Lista las actividades educativas ya asignadas a los miembros
@login_required(login_url="auth/login/")
def lista_educa(request):
    query = request.GET.get('q', '')
    actividades = actividad.objects.filter(
        Q(fechainicio__icontains=query) |  
        Q(fechafin__icontains=query) |      
        Q(duracion__icontains=query) |      
        Q(miembroa__nombre__icontains=query) |   
        Q(miembroa__apellido__icontains=query) | 
        Q(categoria__nombre__icontains=query) |   
        Q(clase__nombre__icontains=query) |      
        Q(maestro__nombre__icontains=query) |    
        Q(curso__nombre__icontains=query) |      
        Q(status__nombre__icontains=query) |     
        Q(tiempo__nombre__icontains=query)        
    )
    context = {
        "active_icon": "actividades",
        "actividades": actividades,
        "query": query,
    }
    return render(request, "actividad/listar_actividades.html", context)



#Llama a la view de la pagina principal para mostrar las opciones o submodulos de actividades
@login_required(login_url="auth/login/")
def actividads(request):
    return render(request, "actividad/actividades.html")


#Agrega a la base de datos los miembros, funcion para insertar 
@login_required(login_url="auth/login/")
def agregar_actividad(request):
    categorias = categoria.objects.all()
    clases = clase.objects.all()
    miembros = miembro.objects.all()
    cursos = curso.objects.all()
    statuses = status.objects.all()
    maestros = maestro.objects.all()
    tiempos = tiempo.objects.all()

    if request.method == 'POST':
        data = request.POST
        try:
            categoria_obj = categoria.objects.get(pk=data['categoria'])
            clase_obj = clase.objects.get(pk=data['clase'])
            miembro_obj = miembro.objects.get(pk=data['miembro'])
            maestro_obj = maestro.objects.get(pk=data['maestro'])
            curso_obj = curso.objects.get(pk=data['curso'])
            status_obj = status.objects.get(pk=data['status'])
            tiempo_obj = tiempo.objects.get(pk=data['tiempo'])

            # Comprobar si el miembro ya está en la misma clase con el mismo curso
            if actividad.objects.filter(miembroa=miembro_obj, curso=curso_obj, clase=clase_obj).exists():
                messages.error(request, 'El miembro ya está asignado en ese curso.', extra_tags="danger")
                return redirect('actividades:agregar_act')

            nueva_actividad = actividad(
                categoria=categoria_obj,
                clase=clase_obj,
                miembroa=miembro_obj,
                maestro=maestro_obj,
                curso=curso_obj,
                status=status_obj,
                tiempo=tiempo_obj,               
                fechainicio=data['fechainicio'],
                duracion=data['duracion'],
                fechafin=data['fechafin']
            )
            nueva_actividad.save()

            messages.success(request, 'Actividad creada con éxito!', extra_tags="success")
            return redirect('actividades:agregar_act')

        except Exception as e:
            messages.error(request, 'Error al crear la actividad: ' + str(e), extra_tags="danger")
            return redirect('actividades:agregar_act')

    return render(request, "actividad/agregar_actividad.html", {
        'categorias': categorias,
        'clases': clases,
        'miembros': miembros,
        'cursos': cursos,
        'statuses': statuses,
        'maestros': maestros,
        'tiempos': tiempos,
    })


#Funcion que devuelve el dato sobre tiempo, dias,semanas y meses
@login_required(login_url="auth/login/")
def get_tiempo_data(request):
    tiempo_id = request.GET.get('tiempo_id')
    try:
        tiempo_obj = tiempo.objects.get(pk=tiempo_id)
        response_data = {'tiempo_nombre': tiempo_obj.nombre}
    except tiempo.DoesNotExist:
        response_data = {'tiempo_nombre': ''}
    
    return JsonResponse(response_data)


#Funcion que lista algunos campos de miembros para poder seleccionarlos y agregarlos a una actividad educativa
@login_required(login_url="auth/login/")
def listar_miem(request):
    query = request.GET.get('q', '')


    miembros = miembro.objects.filter(
        Q(nombre__icontains=query) |
        Q(apellido__icontains=query) |
        Q(genero__nombre__icontains=query) |
        Q(nacionalidad__nombre__icontains=query) |
        Q(edad__icontains=query)
    )

    if query.isdigit():
        miembros = miembros.filter(edad=int(query))
    context = {
        "active_icon": "miembros",
        "miembros": miembros,
        "query": query,
    }
    return render(request, "inicio/home.html", context)



#Funcion que elimina una actividad educativa de la mezquita
@login_required(login_url="auth/login/")
def eliminar_actividades(request, actividad_id):
    try:
        ACtivi = actividad.objects.get(pk=actividad_id)
        ACtivi.delete()
        messages.success(request, '¡Miembro eliminado!', extra_tags="success")
        return redirect('actividades:lista_educativa')  
    except Exception as e:
        messages.error(request, '¡Hubo un error durante la eliminación!' + str(e), extra_tags="danger")
        return redirect('actividades:lista_educativa')



#Funcion actualiza una actividad educativa de la mezquita
@login_required(login_url="auth/login/")
def actualizar_actividad(request, actividad_id):
    categorias = categoria.objects.all()
    clases = clase.objects.all()
    miembros = miembro.objects.all()
    cursos = curso.objects.all()
    statuses = status.objects.all()
    maestros = maestro.objects.all()
    tiempos = tiempo.objects.all()

    try:
        actividad_obj = actividad.objects.get(pk=actividad_id)

        if request.method == 'POST':
            data = request.POST

            # Actualiza los campos de la actividad
            actividad_obj.categoria = categoria.objects.get(pk=data['categoria'])
            actividad_obj.clase = clase.objects.get(pk=data['clase'])
            actividad_obj.miembroa = miembro.objects.get(pk=data['miembro'])
            actividad_obj.maestro = maestro.objects.get(pk=data['maestro'])
            actividad_obj.curso = curso.objects.get(pk=data['curso'])
            actividad_obj.status = status.objects.get(pk=data['status'])
            actividad_obj.tiempo = tiempo.objects.get(pk=data['tiempo'])
            actividad_obj.fechainicio = data['fechainicio']
            actividad_obj.duracion = data['duracion']
            actividad_obj.fechafin = data['fechafin']

            # Comprobar si el miembro ya está en la misma clase con el mismo curso
            if actividad.objects.filter(miembroa=actividad_obj.miembroa, curso=actividad_obj.curso, clase=actividad_obj.clase).exclude(pk=actividad_id).exists():
                messages.error(request, 'El miembro ya está asignado en ese curso.', extra_tags="danger")
                return render(request, 'actividad/actualizar_actividad.html', {
                    'actividad': actividad_obj,
                    'categorias': categorias,
                    'clases': clases,
                    'miembros': miembros,
                    'cursos': cursos,
                    'statuses': statuses,
                    'maestros': maestros,
                    'tiempos': tiempos,
                })

            actividad_obj.save()

            messages.success(request, 'Actividad actualizada con éxito!', extra_tags="success")
            return redirect('actividades:lista_educativa')

        return render(request, 'actividad/actualizar_actividad.html', {
            'actividad': actividad_obj,
            'categorias': categorias,
            'clases': clases,
            'miembros': miembros,
            'cursos': cursos,
            'statuses': statuses,
            'maestros': maestros,
            'tiempos': tiempos,
        })

    except actividad.DoesNotExist:
        messages.error(request, 'La actividad no existe', extra_tags="danger")
        return redirect('actividades:lista_educativa')

    except Exception as e:
        messages.error(request, '¡Hubo un error durante la actualización: ' + str(e), extra_tags="danger")
        return redirect('actividades:lista_educativa')






# ----------------------APARTADO DE MODULO ACTAS MATRIMONIALES-----------------------------------
#------------------------------------------------------------------------------------------------


@login_required(login_url="auth/login/")
def list_actas(request):
    query = request.GET.get('q', '')


    actas = acta.objects.filter(
        Q(titulo__icontains=query) |
        Q(fecha__icontains=query) |
        Q(sheij__icontains=query) |
        Q(novio__icontains=query) |
        Q(novia__icontains=query) |
        Q(guardian__icontains=query) |
        Q(testigos__icontains=query)
    )

    context = {
        "active_icon": "actas",
        "actas": actas,
        "query": query,
    }
    return render(request, "actividad/listar_actas.html", context)



@login_required(login_url="auth/login/")
def agregar_acta(request):
    if request.method == 'POST':
        try:
            titulo = request.POST['titulo']
            novio = request.POST['novio']
            novia = request.POST['novia']

            # Validar si ya existe un acta con el mismo título
            if acta.objects.filter(titulo=titulo).exists():

Comunidad/proyecto/templates/actividad/actividades.html
{% extends 'base/base.html'%}

{% block title%} Actividades {% endblock%}   

{% block background %}{% load static %}{% static 'act/img/activi.jpg' %}{% endblock %}

{% block headers %}
<h1>Actividades</h1>
{% endblock %}

{% block content%}  
 <!-- Proyecto -->
	      <div class="row project">  	
	      	<div class="col-lg-3 col-md-4 offset-lg-1">
			      <img class="img-fluid" src="{% static 'act/img/idi.png' %}" alt="">
	      	</div>
	        <div class="col-lg-7 col-md-8">
	      		<h2 class="section-heading title">Clases de Idioma</h2>   
	          <p> Apartado para mantener un registro ordenado de los miembros que estan asignados a las distinas clases de idiomas que imparte la Comunidad Islámica Aldaawa </p>
                <div class="row ml-0 mb-3">
                    <a href="{% url 'actividades:lista_educativa' %}">
                        <button   style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
                            ADMINISTRAR
                        </button>
                    </a>
                </div>
                <div class="row ml-0 mb-3">
                    <a href="{% url 'actividades:lista_noeducativa' %}">
                        <button  style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
                            (NO MIEMBROS)
                        </button>
                    </a>
                </div>				
	      	</div>
	      </div>
	      <!-- Proyecto -->
	      <div class="row project">  	
	      	<div class="col-lg-3 col-md-4 offset-lg-1">
			      <img class="img-fluid" src="{% static 'act/img/acta.png' %}" alt="">
	      	</div>
	        <div class="col-lg-7 col-md-8">
	      		<h2 class="section-heading title">Actas de Matrimonio</h2>   
	          <p>Apartado para mantener un registro ordenado y seguro de todos los matrimonios que han tenido lugar en la Comunidad Islámica Aldaawa, posteriomente para verificar su validez si asi lo desea</p>
                <div class="row ml-0 mb-3">
                    <a href="{% url 'actividades:list_act' %}">
                        <button style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
                            ADMINISTRAR
                        </button>
                    </a>
                </div>
	      	</div>
	      </div>
{% endblock %}

Comunidad/proyecto/templates/actividad/listar_actas.html
{% extends 'base/base.html' %}
{% load static %}

{% block stylesheets %}
<link href="{% static 'act/css/lista_act.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %} Actas Matrimoniales{% endblock %}
{% block background %}{% static 'act/img/actas.jpg' %}{% endblock %}

{% block headers %}<h1>Lista de Actas Matrimoniales </h1>{% endblock %}

{% block content %}
<div class="row ml-0 mb-3">
    <a href="{% url 'actividades:activi' %}">
        <button type="button" class="btn btn-info font-weight-bold" style= "cursor: pointer;">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            VOLVER
        </button>
    </a>
</div>
<div class="row ml-0 mb-3">
    <a href="{% url 'actividades:actas' %}">
        <button  style= "cursor: pointer;" type="button" class="btn btn-info font-weight-bold">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR NUEVA ACTA
        </button>
    </a>
</div>

<div class="content-container">
    <form method="get" action="{% url 'actividades:list_act' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>
    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
                    <thead>
                    <tr>
                        <th >Titulo</th>
                        <th >Fecha</th>
                        <th >Sheij</th>
                        <th >Novio</th>
                        <th >Novia</th>
                        <th >Guardian</th>
                        <th >Testigos</th>
                        <th >Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for acta in actas %}
                            <tr>
                                <td>{{acta.titulo }}</td>
                                <td>{{ acta.fecha }}</td>
                                <td>{{ acta.sheij }}</td>   
                                <td>{{ acta.novio }}</td>
                                <td>{{ acta.novia }}</td>
                                <td>{{ acta.guardian}}</td>
                                <td>{{ acta.testigos }}</td>
                                <td class="acciones">
                                    <div>
                                        <a href="{% url 'actividades:acta_actuali' acta.id %}" class="btn btn-success" title="Actualizar acta">
                                        ACTUALIZAR
                                        </a>
                                        <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarMiembro{{acta.id }}">
                                        ELIMINAR
                                        </a>
                                    </div>

                                    <div class="modal fade" id="eliminarMiembro{{ acta.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ acta.id}}" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">  
                                                    <h5 class="modal-title" id="exampleModalLabel{{ acta.id }}">Eliminar Acta Matrimonial</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    ¿Está seguro que desea eliminar el Acta Matrimonial: {{ acta.titulo }}?
                                                </div>
                                                <div class="modal-footer">
                                                    <button style="cursor: pointer;" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                                    <a id="updateThisURL" rel="delete" href="{% url 'actividades:eliminar_acta' acta.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
         </table>
    </div>
</div>
{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}

Comunidad/proyecto/templates/actividad/listar_noactividades.html
{% extends 'base/base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static 'act/css/lista_act.css' %}" rel="stylesheet" type="text/css">
{% endblock stylesheets %}

{% block title %}Actividades Educativas{% endblock %}

{% block background %}{% static 'act/img/activi.jpg' %}{% endblock %}

{% block headers %}<h1>Lista No Miembros</h1>{% endblock %}

{% block content %}

<div class="row ml-0 mb-3">
    <a href="{% url 'actividades:activi' %}">
        <button type="button" class="btn btn-info font-weight-bold" style= "cursor: pointer;">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            VOLVER
        </button>
    </a>
</div>

<div class="row ml-0 mb-3">
    <a href="{% url 'actividades:agregar_noact' %}">
        <button type="button" class="btn btn-info font-weight-bold" style= "cursor: pointer;">
            <i class="fas fa-long-arrow-alt-left mr-2"></i>
            AGREGAR NO MIEMBRO 
        </button>
    </a>
</div>


<div class="content-container">
    <form method="get" action="{% url 'actividades:lista_noeducativa' %}">
        <div class="search-bar">
            <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{ query }}" id="search-input">
        </div>
    </form>

    <div id="custom-table" class="table-responsive">
        <table class="custom-table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Edad</th>
                    <th>Nacionalidad</th>
                    <th>Categoria</th>
                    <th>Maestro</th>
                    <th>Clase</th>                    
                    <th>Curso</th>
                    <th>Estado</th>
                    <th>Fecha Inicio</th>
                    <th>Duracion</th>
                    <th>Fecha Finalización</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for act in noactividades %}
                    <tr>
                        <td>{{ act.nombre }}</td>  
                        <td>{{ act.edad }}</td>  
                        <td>{{ act.nacionalidade }}</td>  
                        <td>{{ act.categoria.nombre }}</td> 
                        <td>{{ act.maestro.nombre }}</td> 
                        <td>{{ act.clase.nombre }}</td>                            
                        <td>{{ act.curso.nombre }}</td>      
                        <td>{{ act.status.nombre }}</td>    
                        <td>{{ act.fechainicio }}</td>
                        <td>{{ act.duracion }} {{ act.tiempo.nombre }}</td>    
                        <td>{{ act.fechafin }}</td>
                        <td class="acciones">
                            <div>
                                <a href="{% url 'actividades:noactividad_actuali' act.id %}" class="btn btn-success" title="Actualizar noactividad">
                                    <i class="fas fa-pen"></i> ACTUALIZAR
                                </a>
                                <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#eliminarMiembro{{ act.id }}">
                                   ELIMINAR
                                </a>
                            </div>

                            <div class="modal fade" id="eliminarMiembro{{act.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ act.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">  
                                            <h5 class="modal-title" id="exampleModalLabel{{ act.id}}">Eliminar No Miembro</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Está seguro que desea eliminar al No Miembro: {{ act.nombre }}, de la actividad asignada?
                                        </div>
                                        <div class="modal-footer">
                                            <button style="cursor: pointer;"  type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <a id="updateThisURL" rel="delete" href="{% url 'actividades:eliminar_noactividad' act.id %}" class="btn btn-danger text-decoration-none">Eliminar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block javascripts %}
<script src="{% static 'tables/js/jquery-3.7.0.js' %}"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('search-input');
    const tableRows = document.querySelectorAll('.custom-table tbody tr');

    searchInput.addEventListener('input', function () {
        const query = searchInput.value.toLowerCase();

        tableRows.forEach(function (row) {
            const cells = row.querySelectorAll('td');
            let found = false;

            cells.forEach(function (cell) {
                const cellText = cell.innerText.toLowerCase();
                if (cellText.includes(query)) {
                    found = true;
                }
            });

            if (found) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
});
</script>
{% endblock javascripts %}